### ISSUE TITLE
vscode npm dependency broken: No valid versions available for flatmap-stream

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode-extension-vscode#127]
As of this morning all our vscode extension no longer build. Looks like some dependency changes are the cause. I think a dependency called 'flatmap-stream@0.1.0' was deleted from npm registry. At least, its page returns 404.

https://www.npmjs.com/package/flatmap-stream/v/0.1.0

This dependency is somehow coming into our builds via our dependency on the vscode module.

You can reproduce the problem simply by trying to install vscode as dependency into an empty/fresh node package.

Steps to Reproduce:

1. npm init
2. npm install vscode

=>

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for flatmap-stream

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kdvolder/.npm/_logs/2018-11-26T18_15_02_006Z-debug.log

Attaching contents of the debug log as well:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', 'vscode' ]
2 info using npm@6.4.1
3 info using node@v8.13.0
4 verbose npm-session 0d1478df6d14473d
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/vscode 258ms (from cache)
8 silly pacote tag manifest for vscode@latest fetched in 270ms
9 timing stage:loadCurrentTree Completed in 361ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule vscode@1.1.21 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/gulp-gunzip 75ms (from cache)
18 silly pacote version manifest for gulp-gunzip@1.0.0 fetched in 94ms
19 silly resolveWithNewModule gulp-gunzip@1.0.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/gulp-vinyl-zip 99ms (from cache)
21 http fetch GET 304 https://registry.npmjs.org/gulp-symdest 108ms (from cache)
22 silly pacote range manifest for gulp-vinyl-zip@^2.1.0 fetched in 109ms
23 silly resolveWithNewModule gulp-vinyl-zip@2.1.1 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/gulp-remote-src-vscode 110ms (from cache)
25 silly pacote range manifest for gulp-symdest@^1.1.0 fetched in 114ms
26 silly resolveWithNewModule gulp-symdest@1.1.0 checking installable status
27 silly pacote range manifest for gulp-remote-src-vscode@^0.5.0 fetched in 115ms
28 silly resolveWithNewModule gulp-remote-src-vscode@0.5.0 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/gulp-untar 128ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/gulp-chmod 129ms (from cache)
31 http fetch GET 304 https://registry.npmjs.org/mocha 129ms (from cache)
32 silly pacote range manifest for gulp-untar@^0.0.7 fetched in 132ms
33 silly resolveWithNewModule gulp-untar@0.0.7 checking installable status
34 silly pacote range manifest for gulp-chmod@^2.0.0 fetched in 135ms
35 silly resolveWithNewModule gulp-chmod@2.0.0 checking installable status
36 http fetch GET 304 https://registry.npmjs.org/gulp-filter 134ms (from cache)
37 http fetch GET 304 https://registry.npmjs.org/request 134ms (from cache)
38 silly pacote range manifest for mocha@^4.0.1 fetched in 136ms
39 silly resolveWithNewModule mocha@4.1.0 checking installable status
40 http fetch GET 304 https://registry.npmjs.org/glob 139ms (from cache)
41 silly pacote range manifest for gulp-filter@^5.0.1 fetched in 139ms
42 silly resolveWithNewModule gulp-filter@5.1.0 checking installable status
43 silly pacote range manifest for request@^2.83.0 fetched in 140ms
44 silly resolveWithNewModule request@2.88.0 checking installable status
45 silly pacote range manifest for glob@^7.1.2 fetched in 144ms
46 silly resolveWithNewModule glob@7.1.3 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/semver 53ms (from cache)
48 silly pacote range manifest for semver@^5.4.1 fetched in 56ms
49 silly resolveWithNewModule semver@5.6.0 checking installable status
50 http fetch GET 304 https://registry.npmjs.org/source-map-support 43ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/url-parse 40ms (from cache)
52 silly pacote range manifest for source-map-support@^0.5.0 fetched in 45ms
53 silly resolveWithNewModule source-map-support@0.5.9 checking installable status
54 silly pacote range manifest for url-parse@^1.4.3 fetched in 41ms
55 silly resolveWithNewModule url-parse@1.4.4 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/vinyl-source-stream 41ms (from cache)
57 silly pacote range manifest for vinyl-source-stream@^1.1.0 fetched in 42ms
58 silly resolveWithNewModule vinyl-source-stream@1.1.2 checking installable status
59 http fetch GET 304 https://registry.npmjs.org/fs.realpath 49ms (from cache)
60 http fetch GET 304 https://registry.npmjs.org/inflight 49ms (from cache)
61 http fetch GET 304 https://registry.npmjs.org/path-is-absolute 48ms (from cache)
62 http fetch GET 304 https://registry.npmjs.org/minimatch 50ms (from cache)
63 silly pacote range manifest for fs.realpath@^1.0.0 fetched in 51ms
64 silly resolveWithNewModule fs.realpath@1.0.0 checking installable status
65 silly pacote range manifest for inflight@^1.0.4 fetched in 51ms
66 silly resolveWithNewModule inflight@1.0.6 checking installable status
67 http fetch GET 304 https://registry.npmjs.org/inherits 51ms (from cache)
68 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 51ms
69 silly resolveWithNewModule path-is-absolute@1.0.1 checking installable status
70 silly pacote range manifest for minimatch@^3.0.4 fetched in 52ms
71 silly resolveWithNewModule minimatch@3.0.4 checking installable status
72 silly pacote range manifest for inherits@2 fetched in 52ms
73 silly resolveWithNewModule inherits@2.0.3 checking installable status
74 http fetch GET 304 https://registry.npmjs.org/once 282ms (from cache)
75 silly pacote range manifest for once@^1.3.0 fetched in 285ms
76 silly resolveWithNewModule once@1.4.0 checking installable status
77 http fetch GET 304 https://registry.npmjs.org/wrappy 34ms (from cache)
78 silly pacote range manifest for wrappy@1 fetched in 36ms
79 silly resolveWithNewModule wrappy@1.0.2 checking installable status
80 http fetch GET 304 https://registry.npmjs.org/brace-expansion 32ms (from cache)
81 silly pacote range manifest for brace-expansion@^1.1.7 fetched in 34ms
82 silly resolveWithNewModule brace-expansion@1.1.11 checking installable status
83 http fetch GET 304 https://registry.npmjs.org/concat-map 33ms (from cache)
84 silly pacote version manifest for concat-map@0.0.1 fetched in 35ms
85 silly resolveWithNewModule concat-map@0.0.1 checking installable status
86 http fetch GET 304 https://registry.npmjs.org/balanced-match 59ms (from cache)
87 silly pacote range manifest for balanced-match@^1.0.0 fetched in 61ms
88 silly resolveWithNewModule balanced-match@1.0.0 checking installable status
89 http fetch GET 304 https://registry.npmjs.org/deep-assign 35ms (from cache)
90 silly pacote range manifest for deep-assign@^1.0.0 fetched in 36ms
91 silly resolveWithNewModule deep-assign@1.0.0 checking installable status
92 http fetch GET 304 https://registry.npmjs.org/through2 36ms (from cache)
93 silly pacote range manifest for through2@^2.0.0 fetched in 37ms
94 silly resolveWithNewModule through2@2.0.5 checking installable status
95 http fetch GET 304 https://registry.npmjs.org/stat-mode 286ms (from cache)
96 silly pacote range manifest for stat-mode@^0.2.0 fetched in 288ms
97 silly resolveWithNewModule stat-mode@0.2.2 checking installable status
98 http fetch GET 304 https://registry.npmjs.org/is-obj 39ms (from cache)
99 silly pacote range manifest for is-obj@^1.0.0 fetched in 41ms
100 silly resolveWithNewModule is-obj@1.0.1 checking installable status
101 http fetch GET 304 https://registry.npmjs.org/readable-stream 57ms (from cache)
102 silly pacote range manifest for readable-stream@~2.3.6 fetched in 59ms
103 silly resolveWithNewModule readable-stream@2.3.6 checking installable status
104 http fetch GET 304 https://registry.npmjs.org/xtend 59ms (from cache)
105 silly pacote range manifest for xtend@~4.0.1 fetched in 59ms
106 silly resolveWithNewModule xtend@4.0.1 checking installable status
107 http fetch GET 304 https://registry.npmjs.org/core-util-is 23ms (from cache)
108 silly pacote range manifest for core-util-is@~1.0.0 fetched in 24ms
109 silly resolveWithNewModule core-util-is@1.0.2 checking installable status
110 http fetch GET 304 https://registry.npmjs.org/process-nextick-args 42ms (from cache)
111 silly pacote range manifest for process-nextick-args@~2.0.0 fetched in 44ms
112 silly resolveWithNewModule process-nextick-args@2.0.0 checking installable status
113 http fetch GET 304 https://registry.npmjs.org/string_decoder 43ms (from cache)
114 http fetch GET 304 https://registry.npmjs.org/safe-buffer 45ms (from cache)
115 silly pacote range manifest for string_decoder@~1.1.1 fetched in 45ms
116 silly resolveWithNewModule string_decoder@1.1.1 checking installable status
117 http fetch GET 304 https://registry.npmjs.org/util-deprecate 45ms (from cache)
118 silly pacote range manifest for safe-buffer@~5.1.1 fetched in 47ms
119 silly resolveWithNewModule safe-buffer@5.1.2 checking installable status
120 silly pacote range manifest for util-deprecate@~1.0.1 fetched in 46ms
121 silly resolveWithNewModule util-deprecate@1.0.2 checking installable status
122 http fetch GET 304 https://registry.npmjs.org/isarray 55ms (from cache)
123 silly pacote range manifest for isarray@~1.0.0 fetched in 56ms
124 silly resolveWithNewModule isarray@1.0.0 checking installable status
125 http fetch GET 304 https://registry.npmjs.org/streamfilter 32ms (from cache)
126 http fetch GET 304 https://registry.npmjs.org/multimatch 33ms (from cache)
127 silly pacote range manifest for streamfilter@^1.0.5 fetched in 33ms
128 silly resolveWithNewModule streamfilter@1.0.7 checking installable status
129 silly pacote range manifest for multimatch@^2.0.0 fetched in 34ms
130 silly resolveWithNewModule multimatch@2.1.0 checking installable status
131 http fetch GET 304 https://registry.npmjs.org/plugin-error 53ms (from cache)
132 silly pacote range manifest for plugin-error@^0.1.2 fetched in 55ms
133 silly resolveWithNewModule plugin-error@0.1.2 checking installable status
134 http fetch GET 304 https://registry.npmjs.org/arrify 45ms (from cache)
135 silly pacote range manifest for arrify@^1.0.0 fetched in 46ms
136 silly resolveWithNewModule arrify@1.0.1 checking installable status
137 http fetch GET 304 https://registry.npmjs.org/array-union 77ms (from cache)
138 silly pacote range manifest for array-union@^1.0.1 fetched in 78ms
139 silly resolveWithNewModule array-union@1.0.2 checking installable status
140 http fetch GET 304 https://registry.npmjs.org/array-differ 128ms (from cache)
141 silly pacote range manifest for array-differ@^1.0.0 fetched in 131ms
142 silly resolveWithNewModule array-differ@1.0.0 checking installable status
143 http fetch GET 304 https://registry.npmjs.org/array-uniq 40ms (from cache)
144 silly pacote range manifest for array-uniq@^1.0.1 fetched in 44ms
145 silly resolveWithNewModule array-uniq@1.0.3 checking installable status
146 http fetch GET 304 https://registry.npmjs.org/ansi-cyan 47ms (from cache)
147 http fetch GET 304 https://registry.npmjs.org/arr-diff 47ms (from cache)
148 http fetch GET 304 https://registry.npmjs.org/extend-shallow 46ms (from cache)
149 silly pacote range manifest for ansi-cyan@^0.1.1 fetched in 49ms
150 silly resolveWithNewModule ansi-cyan@0.1.1 checking installable status
151 http fetch GET 304 https://registry.npmjs.org/arr-union 48ms (from cache)
152 silly pacote range manifest for arr-diff@^1.0.1 fetched in 49ms
153 silly resolveWithNewModule arr-diff@1.1.0 checking installable status
154 silly pacote range manifest for extend-shallow@^1.1.2 fetched in 48ms
155 silly resolveWithNewModule extend-shallow@1.1.4 checking installable status
156 silly pacote range manifest for arr-union@^2.0.1 fetched in 50ms
157 silly resolveWithNewModule arr-union@2.1.0 checking installable status
158 http fetch GET 304 https://registry.npmjs.org/ansi-red 94ms (from cache)
159 silly pacote range manifest for ansi-red@^0.1.1 fetched in 96ms
160 silly resolveWithNewModule ansi-red@0.1.1 checking installable status
161 http fetch GET 304 https://registry.npmjs.org/ansi-wrap 51ms (from cache)
162 silly pacote version manifest for ansi-wrap@0.1.0 fetched in 53ms
163 silly resolveWithNewModule ansi-wrap@0.1.0 checking installable status
164 http fetch GET 304 https://registry.npmjs.org/arr-flatten 69ms (from cache)
165 silly pacote range manifest for arr-flatten@^1.0.1 fetched in 71ms
166 silly resolveWithNewModule arr-flatten@1.1.0 checking installable status
167 http fetch GET 304 https://registry.npmjs.org/array-slice 89ms (from cache)
168 silly pacote range manifest for array-slice@^0.2.3 fetched in 92ms
169 silly resolveWithNewModule array-slice@0.2.3 checking installable status
170 http fetch GET 304 https://registry.npmjs.org/kind-of 82ms (from cache)
171 silly pacote range manifest for kind-of@^1.1.0 fetched in 86ms
172 silly resolveWithNewModule kind-of@1.1.0 checking installable status
173 silly pacote range manifest for through2@~0.6.5 fetched in 5ms
174 silly resolveWithNewModule through2@0.6.5 checking installable status
175 http fetch GET 304 https://registry.npmjs.org/vinyl 28ms (from cache)
176 silly pacote range manifest for vinyl@~0.4.6 fetched in 30ms
177 silly resolveWithNewModule vinyl@0.4.6 checking installable status
178 silly pacote range manifest for readable-stream@>=1.0.33-1 <1.1.0-0 fetched in 2ms
179 silly resolveWithNewModule readable-stream@1.0.34 checking installable status
180 silly pacote version manifest for isarray@0.0.1 fetched in 1ms
181 silly resolveWithNewModule isarray@0.0.1 checking installable status
182 silly pacote range manifest for string_decoder@~0.10.x fetched in 1ms
183 silly resolveWithNewModule string_decoder@0.10.31 checking installable status
184 http fetch GET 304 https://registry.npmjs.org/clone 25ms (from cache)
185 silly pacote range manifest for clone@^0.2.0 fetched in 26ms
186 silly resolveWithNewModule clone@0.2.0 checking installable status
187 http fetch GET 304 https://registry.npmjs.org/clone-stats 71ms (from cache)
188 silly pacote range manifest for clone-stats@^0.0.1 fetched in 73ms
189 silly resolveWithNewModule clone-stats@0.0.1 checking installable status
190 silly pacote range manifest for vinyl@^2.0.1 fetched in 9ms
191 silly resolveWithNewModule vinyl@2.2.0 checking installable status
192 http fetch GET 304 https://registry.npmjs.org/node.extend 57ms (from cache)
193 silly pacote range manifest for node.extend@^1.1.2 fetched in 59ms
194 silly resolveWithNewModule node.extend@1.1.8 checking installable status
195 http fetch GET 304 https://registry.npmjs.org/event-stream 61ms (from cache)
196 silly pacote range manifest for event-stream@^3.3.4 fetched in 63ms
197 silly resolveWithNewModule event-stream@3.3.6 checking installable status
198 http fetch GET 304 https://registry.npmjs.org/duplexer 27ms (from cache)
199 silly pacote range manifest for duplexer@^0.1.1 fetched in 28ms
200 silly resolveWithNewModule duplexer@0.1.1 checking installable status
201 http fetch GET 304 https://registry.npmjs.org/flatmap-stream 32ms (from cache)
202 silly fetchPackageMetaData error for flatmap-stream@^0.1.0 No valid versions available for flatmap-stream
203 http fetch GET 304 https://registry.npmjs.org/pause-stream 37ms (from cache)
204 http fetch GET 304 https://registry.npmjs.org/through 37ms (from cache)
205 silly pacote range manifest for pause-stream@^0.0.11 fetched in 38ms
206 silly resolveWithNewModule pause-stream@0.0.11 checking installable status
207 silly pacote range manifest for through@^2.3.8 fetched in 38ms
208 silly resolveWithNewModule through@2.3.8 checking installable status
209 http fetch GET 304 https://registry.npmjs.org/stream-combiner 43ms (from cache)
210 silly pacote range manifest for stream-combiner@^0.2.2 fetched in 44ms
211 silly resolveWithNewModule stream-combiner@0.2.2 checking installable status
212 http fetch GET 304 https://registry.npmjs.org/from 69ms (from cache)
213 silly pacote range manifest for from@^0.1.7 fetched in 70ms
214 silly resolveWithNewModule from@0.1.7 checking installable status
215 http fetch GET 304 https://registry.npmjs.org/map-stream 72ms (from cache)
216 silly pacote version manifest for map-stream@0.0.7 fetched in 74ms
217 silly resolveWithNewModule map-stream@0.0.7 checking installable status
218 http fetch GET 304 https://registry.npmjs.org/split 74ms (from cache)
219 silly pacote range manifest for split@^1.0.1 fetched in 75ms
220 silly resolveWithNewModule split@1.0.1 checking installable status
221 timing stage:rollbackFailedOptional Completed in 1ms
222 timing stage:runTopLevelLifecycles Completed in 2306ms
223 silly saveTree blah@1.0.0
223 silly saveTree └─┬ vscode@1.1.21
223 silly saveTree   ├─┬ glob@7.1.3
223 silly saveTree   │ ├── fs.realpath@1.0.0
223 silly saveTree   │ ├─┬ inflight@1.0.6
223 silly saveTree   │ │ ├─┬ once@1.4.0
223 silly saveTree   │ │ │ └── wrappy@1.0.2
223 silly saveTree   │ │ └── wrappy@1.0.2
223 silly saveTree   │ ├── inherits@2.0.3
223 silly saveTree   │ ├─┬ minimatch@3.0.4
223 silly saveTree   │ │ └─┬ brace-expansion@1.1.11
223 silly saveTree   │ │   ├── balanced-match@1.0.0
223 silly saveTree   │ │   └── concat-map@0.0.1
223 silly saveTree   │ ├── once@1.4.0
223 silly saveTree   │ └── path-is-absolute@1.0.1
223 silly saveTree   ├─┬ gulp-chmod@2.0.0
223 silly saveTree   │ ├─┬ deep-assign@1.0.0
223 silly saveTree   │ │ └── is-obj@1.0.1
223 silly saveTree   │ ├── stat-mode@0.2.2
223 silly saveTree   │ └─┬ through2@2.0.5
223 silly saveTree   │   ├─┬ readable-stream@2.3.6
223 silly saveTree   │   │ ├── core-util-is@1.0.2
223 silly saveTree   │   │ ├── isarray@1.0.0
223 silly saveTree   │   │ ├── process-nextick-args@2.0.0
223 silly saveTree   │   │ ├── safe-buffer@5.1.2
223 silly saveTree   │   │ ├── string_decoder@1.1.1
223 silly saveTree   │   │ └── util-deprecate@1.0.2
223 silly saveTree   │   └── xtend@4.0.1
223 silly saveTree   ├─┬ gulp-filter@5.1.0
223 silly saveTree   │ ├─┬ multimatch@2.1.0
223 silly saveTree   │ │ ├── array-differ@1.0.0
223 silly saveTree   │ │ ├─┬ array-union@1.0.2
223 silly saveTree   │ │ │ └── array-uniq@1.0.3
223 silly saveTree   │ │ └── arrify@1.0.1
223 silly saveTree   │ ├─┬ plugin-error@0.1.2
223 silly saveTree   │ │ ├─┬ ansi-cyan@0.1.1
223 silly saveTree   │ │ │ └── ansi-wrap@0.1.0
223 silly saveTree   │ │ ├── ansi-red@0.1.1
223 silly saveTree   │ │ ├─┬ arr-diff@1.1.0
223 silly saveTree   │ │ │ ├── arr-flatten@1.1.0
223 silly saveTree   │ │ │ └── array-slice@0.2.3
223 silly saveTree   │ │ ├── arr-union@2.1.0
223 silly saveTree   │ │ └─┬ extend-shallow@1.1.4
223 silly saveTree   │ │   └── kind-of@1.1.0
223 silly saveTree   │ └── streamfilter@1.0.7
223 silly saveTree   ├─┬ gulp-gunzip@1.0.0
223 silly saveTree   │ ├─┬ through2@0.6.5
223 silly saveTree   │ │ └─┬ readable-stream@1.0.34
223 silly saveTree   │ │   ├── isarray@0.0.1
223 silly saveTree   │ │   └── string_decoder@0.10.31
223 silly saveTree   │ └─┬ vinyl@0.4.6
223 silly saveTree   │   ├── clone-stats@0.0.1
223 silly saveTree   │   └── clone@0.2.0
223 silly saveTree   ├─┬ gulp-remote-src-vscode@0.5.0
223 silly saveTree   │ ├─┬ event-stream@3.3.6
223 silly saveTree   │ │ ├── duplexer@0.1.1
223 silly saveTree   │ │ ├── from@0.1.7
223 silly saveTree   │ │ ├── map-stream@0.0.7
223 silly saveTree   │ │ ├─┬ pause-stream@0.0.11
223 silly saveTree   │ │ │ └── through@2.3.8
223 silly saveTree   │ │ ├── split@1.0.1
223 silly saveTree   │ │ ├── stream-combiner@0.2.2
223 silly saveTree   │ │ └── through@2.3.8
223 silly saveTree   │ ├── node.extend@1.1.8
223 silly saveTree   │ ├── request@2.88.0
223 silly saveTree   │ └── vinyl@2.2.0
223 silly saveTree   ├── gulp-symdest@1.1.0
223 silly saveTree   ├── gulp-untar@0.0.7
223 silly saveTree   ├── gulp-vinyl-zip@2.1.1
223 silly saveTree   ├── mocha@4.1.0
223 silly saveTree   ├── request@2.88.0
223 silly saveTree   ├── semver@5.6.0
223 silly saveTree   ├── source-map-support@0.5.9
223 silly saveTree   ├── url-parse@1.4.4
223 silly saveTree   └── vinyl-source-stream@1.1.2
224 verbose type range
225 verbose stack flatmap-stream: No valid versions available for flatmap-stream
225 verbose stack     at pickManifest (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:20:11)
225 verbose stack     at fetchPackument.then.packument (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:39:14)
225 verbose stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
225 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
225 verbose stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
225 verbose stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
225 verbose stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
225 verbose stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
225 verbose stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
225 verbose stack     at Immediate.Async.drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
225 verbose stack     at runCallback (timers.js:810:20)
225 verbose stack     at tryOnImmediate (timers.js:768:5)
225 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
226 verbose cwd /home/kdvolder/tmp/blah
227 verbose Linux 4.15.0-39-generic
228 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "vscode"
229 verbose node v8.13.0
230 verbose npm  v6.4.1
231 error code ENOVERSIONS
232 error No valid versions available for flatmap-stream
233 verbose exit [ 1, true ]
```

**Comment by antmak** [comment]
If VSCode was built with  the malicious version of event-stream/flatmap-stream, can it steal my local Copay wallet?

**Comment by bpasero** [comment]
See https://code.visualstudio.com/blogs/2018/11/26/event-stream
