### ISSUE TITLE
Failed to get code binary when testing in environment that needs to use strictSSL:false

### ISSUE THREAD

**Issue by amazingguni** [Microsoft/vscode-extension-vscode#132]
Failed to get code binary when testing in environment that needs to use strictSSL:false

```sh
> taurine@0.0.1 test /home/circleci/repo
> npm run compile && node ./node_modules/vscode/bin/test


> taurine@0.0.1 compile /home/circleci/repo
> tsc -p ./

### VS Code Extension Test Run ###
Current working directory: /home/circleci/repo
Downloading VS Code into "/home/circleci/repo/.vscode-test/stable" from: https://vscode-update.azurewebsites.net/1.30.1/linux-x64/stable
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taurine@0.0.1 test: `npm run compile && node ./node_modules/vscode/bin/test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taurine@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-01-02T09_13_04_956Z-debug.log

```

**Comment by bpasero** [comment]
Fixed via https://github.com/Microsoft/vscode-extension-vscode/commit/e05bf6a07da56b597c9f371efaebe03044f60950
