### ISSUE TITLE
Failed to execute fetch TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by dillonthompson** [microsoft/vscode-extension-vscode#168]
Hi, I am running a MacBook Pro with 10.15.2. with the most recent version of VSCode and am attempting to build my first extension. I initially had issues installing the extension generator because I believe something was wrong with my npm.

I ran the following commands to fix that issue:

```sudo rm -rf /usr/local/lib/node_modules
      sudo rm -rf ~/.npm
      brew install node
```

This seemed to work so I continued with installing the extension generator: 

```npm install -g yo generator-code```

I then ran ```yo code``` and followed the steps to create my extension.

I then proceeded to open the extension in VSCode and attempt to debug it following the steps from the instructions here: [https://code.visualstudio.com/api/get-started/your-first-extension](https://code.visualstudio.com/api/get-started/your-first-extension)

After trying to debug it, I got this little popup in the new VSCode window that opened: [https://prnt.sc/qwhjzr](https://prnt.sc/qwhjzr) <-- screenshot

I then checked my debug console to find the following response:

```
(node:26386) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:26386) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Looking for parseable documents...
Found no documents
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
    at getWorkspaceRootPath (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:5:69)
    at fetch (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:11:10)
    at fetchRemoteUrl (/Users/thompson/.vscode/extensions/fatihacet.gitlab-workflow-2.2.0/src/git_service.js:106:28)
```

Any help would be greatly appreciated! I am really looking forward to hopefully contributing to the VSCode community by building this plugin and maybe more in the future.

Thanks in advance!

**Comment by bpasero** [comment]
@dillonthompson do you have a repository online with your extension code for me to reproduce this error?

**Comment by dillonthompson** [comment]
@bpasero Here is the link to the repo: https://github.com/dillonthompson/green-light-testing

Thanks!

**Comment by bpasero** [comment]
I am able to start the extension (in debug) and execute the "Hello World" command:

![image](https://user-images.githubusercontent.com/900690/73719009-5b9f9f00-471e-11ea-8f9b-48ec18bd54bc.png)

What are your steps to get this error?

**Comment by peni4142** [comment]
Maybe a permission problem? On Ubuntu I had to change the global node_modules location.

**Comment by bpasero** [comment]
OK, so this sounds like a configuration issue on your OS. I have never seen this so far in other issues.
