### ISSUE TITLE
Can't test linux (latest) on CI

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode-extension-vscode#24]
bin/test:98
get https://vscode-update.azurewebsites.net/1.2.1/linux-x64/stable is a `.tar.xz` file and the `test` command is trying to unzip it as `.zip`. 

Relevant travis log part: 
```
$ npm test --silent
### VS Code Extension Test Run ###
Current working directory: /home/travis/build/HookyQR/VSCodeBeautify
Downloading VS Code into "/home/travis/build/HookyQR/VSCodeBeautify/.vscode-test" from: https://vscode-update.azurewebsites.net/1.2.1/linux-x64/stable
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: end of central directory record signature not found
    at /home/travis/build/HookyQR/VSCodeBeautify/node_modules/vscode/node_modules/gulp-vinyl-zip/node_modules/yauzl/index.js:167:14
    at /home/travis/build/HookyQR/VSCodeBeautify/node_modules/vscode/node_modules/gulp-vinyl-zip/node_modules/yauzl/index.js:474:5
    at Object._onImmediate (/home/travis/build/HookyQR/VSCodeBeautify/node_modules/vscode/node_modules/gulp-vinyl-zip/node_modules/yauzl/node_modules/fd-slicer/index.js:200:5)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by bpasero** [comment]
@HookyQR while we are looking into a fix, as a workaround can you specify a dependency to version 1.2.0 in your package.json? That release is still providing a zip.

**Comment by Tyriar** [comment]
@HookyQR this should be working now, let us know if there's any more problems.
