### ISSUE TITLE
vscode module doesn't work from simple script

### ISSUE THREAD

**Issue by Sharpiro** [Microsoft/vscode-extension-vscode#68]
So I have no problem using the vscode node module from the yeoman generated vs code extension.

But is there a reason why the module doesn't seem to work from just a fresh simple script to use for testing?

I get no intellisense errors in code and my vscode.d.ts file is where it should be.

index.ts:
```
import * as vscode from "vscode";
console.log(vscode);
```

index.js:
```
"use strict";
exports.__esModule = true;
var vscode = require("vscode");
console.log(vscode);
```

package.json:
```
{
  "name": "vscodetemp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "postinstall": "node ./node_modules/vscode/bin/install"
  },
  "author": "",
  "license": "ISC",
  "engines": {
    "vscode": "^1.13.0"
  },
  "devDependencies": {
    "vscode": "^1.0.0"
  }
}
```

Exception:
```
  module.js:471
    throw err;
    ^
Error: Cannot find module 'vscode'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\temp\vscodeTemp\index.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by bpasero** [comment]
Sorry, but this is not the right place for questions. Please post questions over at StackOverflow: http://stackoverflow.com/questions/tagged/vscode

Thanks for understanding.
